### ISSUE TITLE
How can I get an api key?

### ISSUE THREAD

**Issue by MoonWanki** [Beaconstac/NearBee-Android-SDK#1]
i want to know how to get an api key and organization id to use this sdk

**Comment by ravipratapm** [comment]
Please sign up for a Premium plan or above on https://www.beaconstac.com

**Comment by janksenhu** [comment]
> i want to know how to get an api key and organization id to use this sdk

you could regist a developer account    []( https://www.beaconstac.com/store/starter-signup)

upper right corner ， click your head ico ，Account ，Developer Token & Organization ID you will found in the site page
