### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by taha1249116** [Beaconstac/NearBee-Android-SDK#2]
Demo/sample application crashes on startScanning.
Log:
Unable to create service co.nearbee.geofence.GeoFenceService: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference

**Comment by shashankraj0202** [comment]
Please use the latest version of NearBee SDK (2.1.9) version 2.1.6 has crash issues.
